config/routes.rb
Rails.application.routes.draw do

  root 'locations#index'
  
  get     'login'   => 'sessions#new',      as: :login
  post    'login'   => 'sessions#create',   as: :create_login
  match   'logout'  => 'sessions#destroy',  as: :logout, via: [:get, :delete]
  
  resources :registrations, only: [:new, :create] do
    get 'activate', on: :member
  end

  # public
  resources :locations, only: :index
  get  'locations/:country_code', to: 'locations#index'
  get  'target_groups/:country_code', to: 'target_groups#index'
  
  # private 
  get 'panel' => redirect('panel/locations')
  post 'evaluate_target' => 'panel/locations#evaluate_target'
  namespace :panel, path: 'panel' do
    resources :locations, only: :index
    get  'locations/:country_code', to: 'locations#index'
    get  'target_groups/:country_code', to: 'target_groups#index'
  end
  
end

app/views/layouts/_flash.html.haml
- flash.each do |type, message|
  .flash{ class: "flash-#{type}", role: "alert" }
    <button type="button" class="close-flash"><span>×</span></button>
    .message= message.html_safe

app/views/layouts/_header.html.haml
%header
  .inner
    - if current_user
      = link_to 'Log out', logout_path, class: 'btn pull-right'
      = link_to 'Panel', panel_path, class: 'btn pull-right'
    - else
      = link_to 'Log in', login_path, class: 'btn pull-right' if controller_name != 'sessions'
      = link_to 'Register', new_registration_path, class: 'btn pull-right'
    = link_to 'Main page', root_path, class: 'btn pull-right'
    .clear-fix

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ :content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type" }/
    %meta{ :charset => "utf-8" }/
    %title Test-dev
    %meta{ :content => "Test-dev", :name => "description" }/
    %meta{ :content => "width=device-width,initial-scale=1.0", :name => "viewport" }/
    /[if lt IE 9]
      <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    
  %body{ class: @panel ? @panel : nil }
    = render 'layouts/header'
    - if flash.any?
      = render 'layouts/flash'
    = yield